jwt:
  secretKey: Q05VLVNQSUNZLUJPQVJELUFQUExJQ0FUSU9OLVNFQ1JFVF9LRVk=
  accessTokenExpirationDay: 100 # AccessToken의 만료기한은 100일로 설정합니다. (변경 가능)

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    open-in-view: false
